### ISSUE TITLE
WebHook support for opening browsers or sharing links

### ISSUE THREAD

**Issue by nkirsch** [Setheck/tweetstreem#8]
In addition to #2 and #3, one could use a web hook to guide

- open a browser on a different machine, helps with #3 
- share a tweet with another medium (i.e. Slack)

**Comment by Setheck** [comment]
client side link support should be sufficient.
I think Slack or chat integration is not on the roadmap. Unless you have a specific feature in mind :D

**Comment by nkirsch** [comment]
👍👍
